version: '3.8'

services:
  # Сервис для базы данных PostgreSQL
  postgres_db:
    image: postgres:14-alpine
    container_name: neo_osi_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME} # Используем переменные из .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Сервис для твоего NestJS-приложения
  backend_app:
    container_name: neo_osi_backend_app
    # Build-контекст указывает на текущую директорию
    build: . 
    restart: always
    # Приложение будет зависеть от базы данных
    depends_on:
      - postgres_db
    ports:
      - "3000:3000" # Пробрасываем порт 3000
    # Указываем, что нужно использовать .env файл
    env_file:
      - .env

volumes:
  postgres_data: